[build]
  publish = "public"
  functions = "functions"
[functions]
  external_node_modules = ["node-fetch"]
  node_bundler = "esbuild"
 
  [functions.download-file]
    timeout = 60
    memory = 1024
