[build]
  publish = "public"
  functions = "functions"
[functions]
  external_node_modules = ["node-fetch", "crypto"]
  node_bundler = "esbuild"
  [functions.upload-file]
    timeout = 30
    memory = 512
  [functions.download-file]
    timeout = 60
    memory = 1024
